### ISSUE TITLE
In windows telnet, Z1 backspace does not work properly

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-secure-iot-stack#12]
Backspace does not move the cursor back in windows telnet

**Comment by donbarnetson** [comment]
More specifically - delete has the function of backspace, delete should delete the current highlighted character

**Comment by sandro2pinto** [comment]
Fixed on commit [13fc267](https://github.com/hex-five/multizone-secure-iot-stack/commit/13fc267b0043bed2cc35a46d2f135107777784c6)
