### ISSUE TITLE
Zone1 (freeRTOS) doesn't show USB attach / detach events.

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#15]

**Comment by sandro2pinto** [comment]
Already reported in issue #4

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/24

**Comment by donbarnetson** [comment]
Confirmed - fixed

**Comment by sandro2pinto** [comment]
Fixed in commit [39ac920](https://github.com/hex-five/multizone-secure-iot-stack/commit/39ac920175727e0206f5145eb3ad199bf5288dff)
