### ISSUE TITLE
Zone1: Load access fault (robot w/ no parameters)

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#17]
Z1 > robot
Load access fault : 0x00000005 0x00000000 0x2041241e

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/24

**Comment by donbarnetson** [comment]
Confirmed - fixed

**Comment by sandro2pinto** [comment]
Fixed in commit [c013cba](https://github.com/hex-five/multizone-secure-iot-stack/commit/c013cbaa00a9a512cf67d93c25fa7e75de2b1e04)
