### ISSUE TITLE
Zone1 line editing doesn't work as expected

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#19]
1) Type "send robot 0" 
2) Type enter
3) Go back to previous history with arrow up
4) move left with left arrow to 'r'
5) backspace to delete "send "
Screen and buffer go out of synch: note the extra white space
6) type enter
7) Go back to previous history with arrow up
Note the extra white space

**Comment by borancar** [comment]
Simpler example:
1. Type "pmp"
2. Move to last p and press backspace
3. You get "p p"
4. Press backspace again and you get " p"
5. Type "pm" and press enter
6. You ended up executing pmp

Conclusion, sometimes backspace works like insert/overwrite space, sometimes like backspace

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/24

**Comment by donbarnetson** [comment]
This appears to be fixed in my tests

**Comment by sandro2pinto** [comment]
Fixed in commit [158a0c2](https://github.com/hex-five/multizone-secure-iot-stack/commit/158a0c26de0dd799d7849fd7192dff58238308d7)
