### ISSUE TITLE
Zone1 (freeRTOS) should send messages to itself to operate the robot

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#2]
Zone1 (freeRTOS) should interact with the robot by sending messages as in the original multizone-sdk demo. Ok to use more meaningful symbolic names for the robot commands - i.e. start / stop rather than 1/0 - but the "send" should not be hidden / replaced with something else. And messages should be processed consistently across zones.

**Comment by borancar** [comment]
Resolved in https://github.com/hex-five/multizone-secure-iot-stack/pull/35, commit https://github.com/hex-five/multizone-secure-iot-stack/pull/35/commits/ae13338e96990bf892921a64f377069b374639b6

**Comment by donbarnetson** [comment]
Confirmed resolved.
