### ISSUE TITLE
Can't ping with packet size >= 1473

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#20]
ping -s 1473 192.168.0.2

**Comment by borancar** [comment]
Known issue, we don't support packets larger than an MTU (1500) bytes. Ping of 1473 bytes is 1501 bytes over the wire:
```
$ ping -s 1473 192.168.0.1
PING 192.168.0.1 (192.168.0.1) 1473(1501) bytes of data.
```

Please close if you agree, otherwise to be written in the documentation.
