### ISSUE TITLE
make load repeatable takes 115 seconds

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-secure-iot-stack#23]
It repeatably takes 115 seconds to push the image to the board with a make load command in my virtualized Ubuntu session - is this just my artifact of virtualization or a broader problem?

**Comment by sandro2pinto** [comment]
Yes Don, virtualization problem - I completely give up from the virtual environment because it used to take ages to load and debug.

**Comment by borancar** [comment]
Looks like a potential hardware emulation vs paravirtualization. My suggestion would be run openocd on Windows and just expose the 4444 and 3333 ports so you can remotely connect from the VM.
