### ISSUE TITLE
X300 multizone.cfg setup

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-secure-iot-stack#25]
In the X300 multizone.cfg, why does Zone 3 have GPIO access?

**Comment by borancar** [comment]
Thanks for the spot, Don. Seems this is a remnant of moving the robot to zone1. I'll handle it as part of moving the RSA private key operations to zone3 (root of trust zone now).

**Comment by borancar** [comment]
Handled as part of https://github.com/hex-five/multizone-secure-iot-stack/pull/24

**Comment by donbarnetson** [comment]
Resolved
