### ISSUE TITLE
Add robot syntax help in Zone1

### ISSUE THREAD

**Issue by sandro2pinto** [hex-five/multizone-secure-iot-stack#28]
It would be nice to have a robot syntax help to let users know the required commands to control the robot.

For example when you type just "robot" or "robot help" you may end having the following reply:

Syntax: robot { q | a | w | s | e | d | r | f | t | g | y }
             'q' - grip close
             'a' - grip open
             'w' - wrist up
             's' - wrist down
             'e' - elbow up
             'd' - elbow down
             'r' - shoulder up
             'f' - shoulder down
             't' - base clockwise
             'g' - base counterclockwise
             'y' - light on

**Comment by cgarlati** [comment]
to simplify, and given that there should be no robot command to start with, the syntax could be displayed upon USB attach - with the adition of the 0 1  >  < options.

**Comment by borancar** [comment]
Sandro and Sergio have already implemented this as part of https://github.com/hex-five/multizone-secure-iot-stack/pull/35, commit https://github.com/hex-five/multizone-secure-iot-stack/pull/35/commits/ae13338e96990bf892921a64f377069b374639b6

**Comment by sandro2pinto** [comment]
Yes - already implemented.

If you type "send 1 h" you will get the syntax - I will move to display once the USB is attached as well.

**Comment by sandro2pinto** [comment]
Fixed in [4740de7](https://github.com/hex-five/multizone-secure-iot-stack/commit/4740de751061cffa80d887a208239f3b106a4403)
