### ISSUE TITLE
Zone1 (freeRTOS) doesn't show interrupt events

### ISSUE THREAD

**Issue by sandro2pinto** [hex-five/multizone-secure-iot-stack#29]

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/24

**Comment by sandro2pinto** [comment]
Fixed in commit [1b69041](https://github.com/hex-five/multizone-secure-iot-stack/commit/b67a9abfc837e2d836ac01feed426a900e3ba986)
