### ISSUE TITLE
Intermittent crashing of Zone 1 TLS session

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-secure-iot-stack#32]
I'm getting intermittent crashing (hang) of zone 1 TLS session - have not been able to find a way to reproduce it.

**Comment by cgarlati** [comment]
Works fine with me

**Comment by cgarlati** [comment]
If the problem is in fact reproduceable it should be threaded as P1

**Comment by donbarnetson** [comment]
Seemed extremely stable in my testing today - closing.
