### ISSUE TITLE
Ping pong doesn't work

### ISSUE THREAD

**Issue by sandro2pinto** [hex-five/multizone-secure-iot-stack#34]

**Comment by borancar** [comment]
This will conflict slightly with Don's requirements in https://github.com/hex-five/multizone-secure-iot-stack/issues/5. e.g. from zone4, should `send 1 p` print the character 1 in zone1 or should it pong zone4 with? At the moment `send 1 p` displays "Z4 > pong" in zone1.

**Comment by sandro2pinto** [comment]
Fixed in [f54a051](https://github.com/hex-five/multizone-secure-iot-stack/commit/f54a05132d5b1f46c79968dd25613165701472b2) and [c3418ef](https://github.com/hex-five/multizone-secure-iot-stack/commit/c3418ef0bfb6cbb8d9e07835eb6a461174f8ec77)
