### ISSUE TITLE
TLS Screen: typying 'k' prints 'KEYUPDATE'

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#36]
Likely a leftover debugging artifact. Please remove any hidden / undocumented / secret commands, key sequences, and similar.

**Comment by borancar** [comment]
Hmm... that wasn't me, but s_client. `-nocommands` disables that feature. @donbarnetson, for the documentation part, I believe the command should be:
```
stty -icanon -echo && openssl s_client -tls1_3 -crlf -nocommands -connect 192.168.1.2:443
```
`-tls1_3` will make a quick failure on openssl versions that don't support TLS.

**Comment by cgarlati** [comment]
Reassigning to Don for inclusion in the documentation:

stty -icanon -echo && openssl s_client -tls1_3 -crlf -nocommands -connect 192.168.1.2:443
