### ISSUE TITLE
Make: cmac.o' given more than once in the same rule

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#37]
make[1]: Entering directory '/home/xxx/multizone-secure-iot-stack/zone3'
../bsp/X300/newlib/newlib.mk:45: target '../ext/wolfssl/wolfcrypt/src/cmac.o' given more than once in the same rule

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/39
