### ISSUE TITLE
Zone4 can't ping itself

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#41]
Zone4 can't ping itself - zone1 works as expected.

**Comment by sandro2pinto** [comment]
Easy fix.

**Comment by cgarlati** [comment]
Still open in RC3

**Comment by sandro2pinto** [comment]
Will raise PR soon!

**Comment by cgarlati** [comment]
Boran to rollup into RC4

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/48, commit https://github.com/hex-five/multizone-secure-iot-stack/pull/48/commits/22afff2eafe8b6fac81ba69a088e87dd1b98b767
