### ISSUE TITLE
Zone4 Timer stops working after pressing BTN

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#44]
Zone4 Timer doesn't work anymore

**Comment by donbarnetson** [comment]
It works in my tests - what aspect is not working for you?

**Comment by sandro2pinto** [comment]
Working as well with me - can you please provide more details?!

**Comment by cgarlati** [comment]
Can't reproduce.

**Comment by cgarlati** [comment]
To reproduce: press BTN3 once. Then timer command stops working.

**Comment by borancar** [comment]
BTN3 is HW wired ot AON on the E300/X300 bitstreams.

**Comment by cgarlati** [comment]
So?

**Comment by borancar** [comment]
It will either stop RTC or reset it. The AON provides the RTC ticks in the E300/X300.

**Comment by borancar** [comment]
So, correction, it wasn't BTN3 but BTN2 that kills the timer. Trying out with BTN3 it doesn't seem to affect the timer at all.

**Comment by borancar** [comment]
@cgarlati, this one looks like a candidate to investigate in the nanokernel. I see the ECALL executing, but the trap handler never gets called.

**Comment by cgarlati** [comment]
@borancar, Any ideas why this happens only with BTN2 and not with BTN1 and BTN0?

**Comment by borancar** [comment]
I think I broke it even with BTN1, just make sure at least 10 interrupts happen.

**Comment by borancar** [comment]
And have broken it with BTN0.

**Comment by borancar** [comment]
Sometimes it may need more than 10 interrupts. Just had one case with BTN0 interrupt happening 10 times but the timer was still working.

**Comment by borancar** [comment]
Broken on an older version of software, the first port to the X300 but using the latest multizone.jar.

**Comment by borancar** [comment]
Broken on the E31, multizone-sdk repo master but using multizone.jar from multizone-secure-iot-stack.

**Comment by cgarlati** [comment]
Issue confirmed also in sandro-one-off (automatic irq enable/disable) multizone.jar

**Comment by cgarlati** [comment]
WORKAROUND: demonstrate timer command before pressing buttons or reboot the board.

**Comment by cgarlati** [comment]
Sandro, per our call: what is the simplest way to reproduce in hex-five/multizone-sdk?

**Comment by sandro2pinto** [comment]
Very easy. Just replace the multizone.jar file from the one delivered in the multizone secure IoT stack. Compile and load and then call the timer command and start pressing several buttons at the same time and you will see at some point in time the timer will never show.

**Comment by cgarlati** [comment]
Fixed in fad5a67
hexfive-kern 81a6f3d
hexfive-conf 2cfeec8
