### ISSUE TITLE
Zone4 still prints "???" for unrecognized chars from Zone2

### ISSUE THREAD

**Issue by sandro2pinto** [hex-five/multizone-secure-iot-stack#45]
If we type "send 2 y" in the Zone4 CLI we will get a message "???".

Correct behavior, agreed/implemented for other zones, would be to not show any char/message.

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/48, commit https://github.com/hex-five/multizone-secure-iot-stack/pull/48/commits/cc3ebba5be0cde9e5c925a69b480730b37905f1c

**Comment by cgarlati** [comment]
Zone 3 needs same fix too

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/49/commits/1172b0d87d9f2a6299233b192b1ea8ea795e3823
