### ISSUE TITLE
Typing "recv 2" in Zone1 CLI lead to inconsistent behavior

### ISSUE THREAD

**Issue by sandro2pinto** [hex-five/multizone-secure-iot-stack#46]
When typing "recv 2" in Zone1 CLI it will just outputs after an enter is pressed (side-effect of mzmsg protocol between Z1-Z2).

**Comment by cgarlati** [comment]
Boran to rollup into RC4

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/48, commit https://github.com/hex-five/multizone-secure-iot-stack/pull/48/commits/1bb052527e422cf47c60d910a827f40c7ddaf490
