### ISSUE TITLE
Double irq messages

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#47]

**Comment by cgarlati** [comment]
press simultaneosly one button and the enter of the command stats: two irq are printed on the screen. same with TLS.

**Comment by borancar** [comment]
I can reproduce without using stats. I just press BTN_0, BTN_1, BTN_2, BTN_1, BTN_0 in a row. At least one will get printed twice.

**Comment by cgarlati** [comment]
Confirmed on zone4 / uart too. no need to stats: just press the three button in sequence.

**Comment by cgarlati** [comment]
Boran to rollup into RC4

**Comment by borancar** [comment]
Fixed in https://github.com/hex-five/multizone-secure-iot-stack/pull/48, commit https://github.com/hex-five/multizone-secure-iot-stack/pull/48/commits/e7e49df587dfc1c80dd17cb07cbfb4e22d644f10

**Comment by borancar** [comment]
Debounce and the light on now at 500ms.

**Comment by borancar** [comment]
FYI, double interrupts reproduced on the E31, multizone-sdk master but using latest multizone.jar from multizone-secure-iot-stack.
