### ISSUE TITLE
Clean up picoTCP warnings and unresolved includes 

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#50]
Remove from the picoTCP code tree any redundant components (i.e. platforms) that otherwise cause unresolved includes in Eclipse projects.

**Comment by cgarlati** [comment]
@borancar Any updates?

**Comment by borancar** [comment]
Started work just now.

**Comment by borancar** [comment]
Done in https://github.com/hex-five/multizone-secure-iot-stack/pull/56.
