### ISSUE TITLE
Bump to hexfive-lib v1.1.0

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#54]
Enhanced ECALL_SEND() / ECALL_RECEIVE()

@borancar remove mzmsg complexity / overhead

**Comment by borancar** [comment]
Done in https://github.com/hex-five/multizone-secure-iot-stack/pull/56.

mzmsg_write and mzmsg_read still remain as there needs to be a write/read function that splits the transfer into chunks. Happy to rename if you could provide me with a better name.

Future-wise, there's a potential to abstract it behind a file descriptor with queues and implement read/write functions.

**Comment by cgarlati** [comment]
Please rename msg_write() and msg_read()

**Comment by borancar** [comment]
Done in https://github.com/hex-five/multizone-secure-iot-stack/pull/56/commits/6269239549a5869d09716be74f167fa4fe7ff44d.
