### ISSUE TITLE
Makefile:51: recipe for target 'all' failed

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-secure-iot-stack#63]
@borancar build fails with no meaningful message if the wolfssl submodule is empty or not initialized. Suggest adding a super-simple check in the make file with relative meaningful message - something like "Git submodule not initialized - try 'git submodule update --init --recursive'" Thanks! Cesare

and let's add an entry to the FAQ page on www.hex-five.com

**Comment by borancar** [comment]
Handled in https://github.com/hex-five/multizone-secure-iot-stack/pull/64

**Comment by cgarlati** [comment]
To be merged
