### ISSUE TITLE
Zone 1 exec 20410000 causes crash

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-secure-iot-stack#7]
issuing an exec command to Z1 flash base 20410000 address causes zone 1 to crash

**Comment by sandro2pinto** [comment]
'exec' command removed - such as 'timer' it doesn't make sense in the context of FreeRTOS

**Comment by cgarlati** [comment]
Somehow agree with regard to the soft timer. Disagree on exec.

**Comment by borancar** [comment]
Can you describe the crash more? What I was experiencing was telnet hang, but zone1 was still running the LED through the rainbow pattern and the robot light was responding to robot on/off. The telnet hang would be a result of not properly resetting the mzmsg communication.

**Comment by donbarnetson** [comment]
Agreed - yes, it was a telnet hang; but now that command is removed it is a moot point.

**Comment by donbarnetson** [comment]
exec has been removed; issue is closed.
